### ISSUE TITLE
Implement A2A (Agent-to-Agent) Architecture for Clinical Protocol Extraction Pipeline

### ISSUE THREAD

**Issue by jmjlacosta** [jmjlacosta/clinical-protocol-ui-minimal#1]
# Implement A2A (Agent-to-Agent) Architecture for Clinical Protocol Extraction Pipeline

## Overview
Transform the current monolithic extraction pipeline into a distributed Agent-to-Agent (A2A) system following Google's A2A protocol standards. This should be built in parallel with the existing system to maintain functionality during development.

## Background
The repository currently has two approaches:
1. **Monolithic pipeline** (`incremental_extractor/` and `unified_extractor_enhanced.py`)
2. **Agent-based pipeline** (`agents/` folder with orchestrator)

The agent-based approach already has the foundation for A2A but currently uses direct function calls instead of the A2A protocol.

## What is A2A?
Agent-to-Agent (A2A) is a standardized protocol released by Google in 2025 that enables AI agents to:
- Discover each other's capabilities via Agent Cards
- Communicate using HTTP/JSON-RPC
- Handle long-running tasks with SSE (Server-Sent Events)
- Work across different platforms and vendors
- Maintain security and authentication

### Existing Agents
1. **ingestion_ocr/** - Processes PDFs and performs OCR
2. **chunker_indexer/** - Chunks text into manageable pieces
3. **outcome_extractor/** - Extracts clinical outcomes
4. **orchestrator/** - Coordinates the pipeline

### Current Flow (in orchestrator/main.py)
```python
# Direct function calls between agents
ingest = run_ingest(pdf_bytes)
chunk_res = run_chunker(ingest)
outcome_res = run_outcomes(chunk_res.chunks)
```

### Phase 1: Create A2A Infrastructure
1. **Create base A2A agent class**
   - Implement A2A protocol handlers
   - JSON-RPC request/response
   - SSE for long-running tasks
   - Agent Card generation

2. **Set up service discovery**
   - Agent registry service
   - Dynamic agent discovery
   - Health checks

#### For each agent (ingestion, chunker, outcome_extractor):

1. **Create Agent Card** (`/.well-known/agent.json`)
```json
{
  "name": "ingestion-ocr-agent",
  "description": "Processes PDF documents and performs OCR",
  "version": "1.0.0",
  "capabilities": [
    {
      "name": "process_pdf",
      "description": "Extract text from PDF using OCR",
      "input_schema": {...},
      "output_schema": {...}
    }
  ],
  "endpoint": "http://localhost:8001",
  "auth": {
    "type": "bearer",
    "scheme": "OpenAPI"
  }
}
```

2. **Create HTTP endpoints**
   - POST /tasks - Accept new tasks
   - GET /tasks/{id} - Check task status
   - GET /tasks/{id}/events - SSE stream for updates

3. **Implement A2A task handlers**
   - Parse A2A task requests
   - Execute existing logic
   - Return A2A-compliant responses

### Phase 3: Update Orchestrator

1. **Replace direct calls with A2A requests**
```python
# Old way
ingest = run_ingest(pdf_bytes)

# New A2A way
ingest_task = await a2a_client.send_task(
    agent_url="http://ingestion-agent:8001",
    task={
        "name": "process_pdf",
        "input": {"pdf_bytes": pdf_bytes}
    }
)
ingest = await ingest_task.get_result()
```

2. **Add agent discovery**
   - Fetch agent cards on startup
   - Handle agent availability
   - Implement fallback strategies

### Phase 4: Deployment Configuration

1. **Create Docker setup**
```yaml
# docker-compose.a2a.yml
version: '3.8'
services:
  ingestion-agent:
    build: ./agents/ingestion_ocr
    ports:
      - "8001:8001"
    environment:
      - A2A_PORT=8001
      - A2A_NAME=ingestion-ocr-agent
  
  chunker-agent:
    build: ./agents/chunker_indexer
    ports:
      - "8002:8002"
    environment:
      - A2A_PORT=8002
      - A2A_NAME=chunker-indexer-agent
  
  outcome-agent:
    build: ./agents/outcome_extractor
    ports:
      - "8003:8003"
    environment:
      - A2A_PORT=8003
      - A2A_NAME=outcome-extractor-agent
  
  orchestrator:
    build: ./agents/orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - ingestion-agent
      - chunker-agent
      - outcome-agent
```

2. **Add Kubernetes manifests** (optional)
   - Service definitions
   - Deployments with scaling
   - ConfigMaps for agent cards

### Phase 5: Testing & Migration

1. **Parallel operation**
   - Keep existing monolithic code unchanged
   - Add feature flag to switch between modes
   - Compare outputs between systems

2. **Integration tests**
   - Test agent discovery
   - Verify A2A communication
   - Validate error handling

3. **Performance testing**
   - Measure latency vs monolithic
   - Test scaling capabilities
   - Monitor resource usage

### Dependencies
- FastAPI or similar for HTTP endpoints
- JSON-RPC library
- SSE support (e.g., fastapi-sse)
- Service discovery (consul, etcd, or custom)

### File Structure
```
agents/
├── base/
│   ├── __init__.py
│   ├── a2a_agent.py      # Base A2A agent class
│   ├── a2a_client.py     # A2A client for orchestrator
│   └── protocols.py      # A2A protocol definitions
├── ingestion_ocr/
│   ├── Dockerfile
│   ├── agent_card.json
│   ├── a2a_server.py     # A2A endpoint handlers
│   └── [existing files]
├── chunker_indexer/
│   └── [similar structure]
├── outcome_extractor/
│   └── [similar structure]
└── orchestrator/
    ├── a2a_orchestrator.py  # New A2A-based orchestrator
    └── [existing files]
```

## Success Criteria
1. All agents expose A2A-compliant endpoints
2. Orchestrator can discover and communicate with agents via A2A
3. System produces identical results to monolithic pipeline
4. Agents can be independently deployed and scaled
5. No loss of existing functionality

## Notes for Implementation
- Start with one agent (e.g., chunker) as proof of concept
- Use environment variables for agent URLs during development
- Implement comprehensive logging for debugging A2A communication
- Consider using OpenTelemetry for distributed tracing
- Maintain backward compatibility with existing UI

## References
- [Google A2A Protocol Specification](https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/)
- [A2A vs MCP Comparison](https://www.kdnuggets.com/building-ai-agents-a2a-vs-mcp-explained-simply)
- Current orchestrator implementation: `agents/orchestrator/main.py`

## Do NOT
- Remove or modify existing monolithic code
- Break current functionality
- Deploy A2A version as default initially
- Replace the system until explicitly instructed

This implementation should coexist with the current system until we validate it works correctly and performs well.
